Fix: Every TOC entry has leading dots to page num.
cardi/USCthesis pull request #4
Opened 2023-04-11 03:11 UTC by valeriu-balaban

USC thesis guidelines require "Every entry on the TOC needs leading dots going to each page number."

Added `tocloft` commands to include dots for chapters based on the chapter font styles, bold or medium-weight.

2023-04-18 19:28 UTC, cardi commented
Thank you for this patch!

Are the guidelines you mentioned specific to a particular school or department? I couldn't find leading dots requirement for the [Graduate School](https://graduateschool.usc.edu/wp-content/uploads/2020/11/Manuscript_Formatting_and_Documentation_Styles.pdf) (the sample TOC in Appendix B has leading dots on top-level entries but the dots aren't mentioned in page 4).

I'm wondering if the leading dots should be a toggle if it's a requirement for some departments and optional for others.

2023-04-20 07:29 UTC, dstripelis commented
Leading dots for every entry in TOC was required in my case as well (submitted the thesis two weeks ago). I think this is a general requirement and not department specific.

To add the leading dots, I added the following two commands after all `\usepackage{...}` commands:
```
\renewcommand{\cftpartleader}{\cftdotfill{\cftdotsep}} % for parts
\renewcommand{\cftchapleader}{\cftdotfill{\cftdotsep}} % for chapters
```

2023-04-20 21:26 UTC, valeriu-balaban commented
General requirement requested by the USC Graduate School. 

The wording of the change requested was: "Every entry on the TOC needs leading dots going to each page number."

2023-04-26 03:33 UTC, cardi requested changes

2023-04-26 03:33 UTC, cardi commented on USCthesis.sty
> +\renewcommand\cftchapdotsep{\cftdotsep}	   % add dots in between capter names
nit: capter -> chapter

2023-04-26 03:37 UTC, cardi commented
Thank you both for the requirement update (FWIW, my thesis in 2020 did not have dots in the TOC chapter entries, but perhaps the school is enforcing style guidelines more stringently now).

2023-05-11 18:23 UTC, merged